Dz11
ShadMaxim/ShadchnevAndroidPvt pull request #11
Opened 2019-07-22 23:07 UTC by ShadMaxim

2019-07-24 10:56 UTC, 3RUN approved these changes

2019-07-25 22:24 UTC, tim-teacher requested changes

2019-07-25 22:24 UTC, jushlwest commented on app/src/main/java/by/itacademy/myapp/dz11/mvp/details/Dz11BasePresenterDetails.kt
> +    fun getId(idStudent: Long)
я так понимаю это должно быть setId а не get?

2019-07-25 22:24 UTC, jushlwest commented on app/src/main/java/by/itacademy/myapp/dz11/mvp/details/Dz11DetailsFragment.kt
> +            showStudent(Dz11DataStudent.findStudentById(idStudent), view.findViewById(R.id.dz8AvatarProfileImageView))
Почему вы showStudent делаете из фрагмента а не из презентера? Фрагмент вообще не должен знать о вашем синглтоне Dz11DataStudent

2019-07-25 22:24 UTC, jushlwest commented on app/src/main/java/by/itacademy/myapp/dz11/mvp/edit/Dz11EditFragment.kt
> +    override fun correctDataFilling(name: String, age: Int, url: String): Boolean {
этот метод лучше в презентер вынести

2019-07-25 22:24 UTC, jushlwest commented on app/src/main/java/by/itacademy/myapp/dz11/mvvm/Dz11Activity.kt
> +        viewModel.drawMap()
Map - это view, во VM ничего не должно быть с картой связанного

2019-07-25 22:24 UTC, jushlwest commented on app/src/main/java/by/itacademy/myapp/dz11/mvvm/Dz11Activity.kt
> +        Handler().postDelayed({
ой ой ой, убираем хендлер. Во первых если уж используете хендле так хоть отписку сделайте. А вообще он не нужен, что за 600 млс??? почему не 1000 или 200? если пришлось такое написать то явно с логикой что то не так

2019-07-27 20:56 UTC, tim-teacher requested changes
Совсем чуть чуть пофиксить)

2019-07-27 20:56 UTC, jushlwest commented on app/src/main/java/by/itacademy/myapp/dz11/mvp/details/Dz11DetailsFragment.kt
> +    private var student: Dz6Student? = null
студента отсюда убираем, он же уже есть в презентере

2019-07-27 20:56 UTC, jushlwest commented on app/src/main/java/by/itacademy/myapp/dz11/mvp/details/Dz11DetailsFragment.kt
> +            student = presenter.getStudentById(idStudent)
это не MVP, в этой реализации презентер ничем не отличается от Dz11DataStudent. У вас должен быть тут только вызов метода в презентере а затем презентер уже сам вызовыет у Фрагмента нужный метод

2019-07-27 20:56 UTC, jushlwest commented on app/src/main/java/by/itacademy/myapp/dz11/mvp/details/Dz11DetailsFragment.kt
> +    override fun showStudent(student: Dz6Student) {
вот этот метод, непонятно зачем тогда вам выше было получать студента, имею ввид 64 строку

2019-07-27 20:56 UTC, jushlwest commented on app/src/main/java/by/itacademy/myapp/dz11/mvp/edit/Dz11EditFragment.kt
> +    // private var student: Dz6Student? = null
комменты удаляем

2019-07-27 20:56 UTC, jushlwest commented on app/src/main/java/by/itacademy/myapp/dz11/mvp/edit/Dz11PresenterEdit.kt
> +    private lateinit var student: Dz6Student
удаляем

2019-07-28 19:40 UTC, tim-teacher approved these changes

2019-07-28 19:41 UTC, merged