Dz12
ShadMaxim/ShadchnevAndroidPvt pull request #12
Opened 2019-08-03 12:05 UTC by ShadMaxim

таймер в Dz12PresenterList

2019-08-04 08:45 UTC, tim-teacher requested changes
Убрать синглтон и сделать отписки

2019-08-04 08:45 UTC, jushlwest commented on app/src/main/java/by/itacademy/myapp/dz12/student/list/Dz12PresenterList.kt
> +                Dz12StudentsSinglton.createStudentsList(data)
весь функционал из Dz12StudentsSinglton должен быть перенесен в репозиторий, а то у вас целая паутина действич, презентер фактичиски стал главным логическим модулем который объединяет данные

2019-08-04 08:45 UTC, jushlwest commented on app/src/main/java/by/itacademy/myapp/dz12/cars/Dz12ViewModel.kt
> +        disposable = carRepository
отписаться забыли

2019-08-04 08:45 UTC, jushlwest commented on app/src/main/java/by/itacademy/myapp/dz12/student/details/Dz12PresenterDetails.kt
> +        disposable = repository
а где отписка?

2019-08-06 09:40 UTC, tim-teacher requested changes

2019-08-06 09:40 UTC, jushlwest commented on app/src/main/java/by/itacademy/myapp/dz12/cars/Dz12ViewModel.kt
> +        disposable = carRepository
так и не вижу где отписываетесь)

2019-08-06 09:40 UTC, jushlwest commented on app/src/main/java/by/itacademy/myapp/dz12/student/details/Dz12BasePresenterDetails.kt
> +    fun deleteOfServerAndSingleton(idStudent: String)
странное название метода)

2019-08-06 09:40 UTC, jushlwest commented on app/src/main/java/by/itacademy/myapp/dz12/student/model/datasingleton/Dz12StudentsSinglton.kt
> +object Dz12StudentsSinglton {
удаляйте это, зачем на комментированный код в master ветке

2019-08-06 10:21 UTC, ShadMaxim commented
отписываюсь в onDestroy v Activity

2019-08-10 10:03 UTC, tim-teacher approved these changes

2019-08-10 10:32 UTC, merged