Dz1
ShadMaxim/ShadchnevAndroidPvt pull request #2
Opened 2019-06-17 12:57 UTC by ShadMaxim

2019-06-17 13:03 UTC, Serggiolysen approved these changes

2019-06-17 13:03 UTC, Serggiolysen commented on app/src/main/res/layout/activity_dz1.xml
> +                        android:layout_width="72sp"
Может расстояния лучше в относительных точках делать (dp)

2019-06-17 19:50 UTC, stopstress approved these changes

2019-06-17 19:50 UTC, stopstress commented on app/src/main/res/layout/activity_dz1.xml
> +                        android:layout_width="72sp"
Наверное да: sp "поплывут", если пользователь поменяет настройки отображения.

2019-06-18 11:08 UTC, jushlwest commented on app/src/main/res/layout/activity_dz1.xml
> +                        android:layout_width="72sp"
Ага, sp используются только для размеров текста. Для всех остальных размеров используем dp

2019-06-18 11:11 UTC, tim-teacher requested changes
TextView нужно убрать и заменить на что то попроще, View например

2019-06-18 11:11 UTC, jushlwest commented on app/src/main/res/layout/activity_dz1.xml
> +            <TextView
зачем тут TextView? вы же не используете никакое отображения текста тут

2019-06-18 11:53 UTC, closed without merging