Dz6
ShadMaxim/ShadchnevAndroidPvt pull request #8
Opened 2019-07-03 20:38 UTC by ShadMaxim

2019-07-04 19:33 UTC, 3RUN approved these changes

2019-07-05 12:17 UTC, tim-teacher requested changes

2019-07-05 12:17 UTC, jushlwest commented on app/src/main/java/by/itacademy/myapp/dz6/Dz6Student.kt
> +class Dz6Student(id: Long, url: String, name: String, age: Int) {
просто добавте тут каждой переменной val и не нужно снизу сеттить их, а то выглядит как то странно даже для java

2019-07-05 12:17 UTC, jushlwest commented on app/src/main/java/by/itacademy/myapp/dz6/Dz6StudentDetailsActivity.kt
> +    lateinit var student: Dz6Student
а если null?

2019-07-05 12:17 UTC, jushlwest commented on app/src/main/java/by/itacademy/myapp/dz6/Dz6StudentEditActivity.kt
> +    lateinit var name: String
думаю эти переменные можно внутри метода написать локально, и если нужно передать в другой метод как аргументы

2019-07-05 12:17 UTC, jushlwest commented on app/src/main/java/by/itacademy/myapp/dz6/Dz6StudentEditActivity.kt
> +    private lateinit var student: Dz6Student
опять же а если null?

2019-07-05 13:51 UTC, tim-teacher approved these changes

2019-07-06 11:27 UTC, merged